### ISSUE TITLE
Bye, bye Gulpjs

### ISSUE THREAD

**Issue by feliun** [guidesmiths/generator-systemic#15]

**Comment by UlisesGascon** [comment]
### TODO:
- [ ] Remove Gulp tasks and use NPM Scripts
- [ ] Extend NSP Task with npm audit
- [ ] Migrate linting and linting fix
- [ ] Migrate tests
- [ ] Let's add Husky hooks
