### ISSUE TITLE
Migration to swagger-endpoint-validator

### ISSUE THREAD

**Issue by UlisesGascon** [guidesmiths/generator-systemic#27]
### Todo:

- [ ] Remove dependency `express-swagger-generator`
- [ ] Added dependency `swagger-endpoint-validator`
- [ ] Update the template
